# Generated by Django 5.0.6 on 2024-07-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='imagens_esperadas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
