# Generated by Django 5.0.6 on 2024-07-03 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_cursos_imagens_esperadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='imagens_esperadas',
            field=models.TextField(blank=True, null=True, verbose_name='Descrições do que é esperado nas imagens (Virgula para separar)'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='instituicao',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='professor',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Professor'),
        ),
    ]
