"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path, os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i1jh60052jm*r0gspx6#3jz8wb#a*!-hl-a@yhtr8gxr1by*xd'

# os.environ['BING_SEARCH_V7_SUBSCRIPTION_KEY'] = '93d143d465e842c0bbf320521cb91171'
# os.environ['BING_SEARCH_V7_ENDPOINT'] = 'https://api.bing.microsoft.com'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Define o tempo limite HTTP em segundos
HTTP_TIMEOUT = 300

ALLOWED_HOSTS = ['https://www.aidaimg.com', 'https://aidaimg.com', 'www.aidaimg.com','aidaimg.com','54.94.175.177', 'localhost', '127.0.0.1', '0.0.0.0', '172.31.6.108', '54.233.148.161']

CSRF_TRUSTED_ORIGINS = ['https://www.aidaimg.com', 'https://aidaimg.com']

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'galeria.apps.GaleriaConfig',
    'usuarios.apps.UsuariosConfig',
    'cursos.apps.CursosConfig',
    'storages',
]

#
ASGI_APPLICATION = 'setup.asgi.application'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'galeria.middleware.TimeoutMiddleware',
]

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

# AWS Configuração
AWS_ACCESS_KEY_ID = 'AKIAQ3EGWCE7VNGCF3FM'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'bucketaidaimg'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_DEFAULT_ACL = 'public-read'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400'
}
AWS_LOCATION = 'static'
AWS_QUERYSTRING_AUTH = False
AWS_HEADERS = {
    'Access-Control-Allow-Origin': '*',
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/





# # Condicional para definir as configurações de MEDIA_ROOT quando a URL é local
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# #DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
# STATIC_URL = '/static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Diretório onde seus arquivos estáticos estão durante o desenvolvimento
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Diretório onde os arquivos estáticos coletados são armazenados para produção


# MEDIA_URL = 'http://127.0.0.1:8000/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'setup/static']
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# messages
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
    messages.SUCCESS: 'success',
}

# DEFAULT_FILE_STORAGE: Padrão para usar o sistema de arquivos local para armazenar arquivos
# DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# FILE_UPLOAD_MAX_MEMORY_SIZE: Tamanho máximo de um arquivo enviado em memória (antes de ser salvo em arquivo temporário)
# FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB

# DATA_UPLOAD_MAX_MEMORY_SIZE: Tamanho máximo para dados de uma solicitação de upload em memória
