# Generated by Django 5.0.2 on 2024-04-17 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_fotografia_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='usuario',
        ),
    ]
