# Generated by Django 5.0.2 on 2024-04-17 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('galeria', '0008_remove_fotografia_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='curso',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos'),
        ),
    ]
