# Generated by Django 5.0.2 on 2024-04-24 18:09

import django.db.models.deletion
import galeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('galeria', '0009_fotografia_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('imagem', models.ImageField(upload_to=galeria.models.upload_to, verbose_name='Imagem')),
                ('class_sis', models.CharField(choices=[('IDA_igual', 'IDA Igual'), ('IDA_mono', 'IDA Mono'), ('IDA_copia', 'IDA Cópia'), ('IDA_copia_web', 'IDA Cópia Web'), ('IDA_class', 'IDA Class')], default='IDA_igual', max_length=20, verbose_name='Classificação Sistema')),
                ('class_prof', models.CharField(choices=[('IDA_igual', 'IDA Igual'), ('IDA_mono', 'IDA Mono'), ('IDA_copia', 'IDA Cópia'), ('IDA_copia_web', 'IDA Cópia Web'), ('IDA_class', 'IDA Class')], default='IDA_igual', max_length=20, verbose_name='Classificação Professor')),
                ('obs_class_sis', models.CharField(max_length=100, verbose_name='Observações Sistema')),
                ('obs_class_prof', models.CharField(max_length=100, verbose_name='Observações Professor')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Curso')),
            ],
        ),
        migrations.DeleteModel(
            name='Fotografia',
        ),
    ]
