# Generated by Django 5.0.2 on 2024-04-24 23:25

import django.db.models.deletion
import galeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('galeria', '0010_imagenscurso_delete_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenscurso',
            name='class_prof',
            field=models.CharField(blank=True, choices=[('IDA_igual', 'IDA Igual'), ('IDA_mono', 'IDA Mono'), ('IDA_copia', 'IDA Cópia'), ('IDA_copia_web', 'IDA Cópia Web'), ('IDA_class', 'IDA Class')], default='IDA_igual', max_length=20, null=True, verbose_name='Classificação Professor'),
        ),
        migrations.AlterField(
            model_name='imagenscurso',
            name='class_sis',
            field=models.CharField(blank=True, choices=[('IDA_igual', 'IDA Igual'), ('IDA_mono', 'IDA Mono'), ('IDA_copia', 'IDA Cópia'), ('IDA_copia_web', 'IDA Cópia Web'), ('IDA_class', 'IDA Class')], default='IDA_igual', max_length=20, null=True, verbose_name='Classificação Sistema'),
        ),
        migrations.AlterField(
            model_name='imagenscurso',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='imagenscurso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=galeria.models.upload_to, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='imagenscurso',
            name='nome_arquivo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo'),
        ),
        migrations.AlterField(
            model_name='imagenscurso',
            name='obs_class_prof',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações Professor'),
        ),
        migrations.AlterField(
            model_name='imagenscurso',
            name='obs_class_sis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações Sistema'),
        ),
    ]
