# Generated by Django 5.0.2 on 2024-05-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0012_alter_imagenscurso_class_prof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
    ]
