# Generated by Django 5.0.6 on 2024-05-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0013_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
