# Generated by Django 5.0.6 on 2024-05-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0014_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenscurso',
            name='class_prof',
            field=models.CharField(blank=True, choices=[('IDA_igual', 'IDA Igual'), ('IDA_mono', 'IDA Mono'), ('IDA_copia', 'IDA Cópia'), ('IDA_copia_web', 'IDA Cópia Web'), ('IDA_class', 'IDA Class'), ('Normal', 'Normal')], default=None, max_length=20, null=True, verbose_name='Classificação Professor'),
        ),
        migrations.AlterField(
            model_name='imagenscurso',
            name='class_sis',
            field=models.CharField(blank=True, choices=[('IDA_igual', 'IDA Igual'), ('IDA_mono', 'IDA Mono'), ('IDA_copia', 'IDA Cópia'), ('IDA_copia_web', 'IDA Cópia Web'), ('IDA_class', 'IDA Class'), ('Normal', 'Normal')], default=None, max_length=20, null=True, verbose_name='Classificação Sistema'),
        ),
    ]
