# Generated by Django 5.0.6 on 2024-08-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0016_alter_imagenscurso_class_prof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenscurso',
            name='caracteristicas',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagenscurso',
            name='class_prof',
            field=models.CharField(blank=True, choices=[('IDA_igual', 'IDA Igual'), ('IDA_mono', 'IDA Mono'), ('IDA_copia', 'IDA Cópia'), ('IDA_copia_web', 'IDA Cópia Web'), ('IDA_class', 'IDA Class'), ('Normal', 'Normal'), ('Normal Esperado', 'Normal Esperado')], default=None, max_length=20, null=True, verbose_name='Classificação Professor'),
        ),
        migrations.AlterField(
            model_name='imagenscurso',
            name='class_sis',
            field=models.CharField(blank=True, choices=[('IDA_igual', 'IDA Igual'), ('IDA_mono', 'IDA Mono'), ('IDA_copia', 'IDA Cópia'), ('IDA_copia_web', 'IDA Cópia Web'), ('IDA_class', 'IDA Class'), ('Normal', 'Normal'), ('Normal Esperado', 'Normal Esperado')], default=None, max_length=20, null=True, verbose_name='Classificação Sistema'),
        ),
    ]
